

- name: Add docker repo key (Ubuntu)
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9
  when: ansible_lsb.id=="Ubuntu"

- name: Add docker repo (Ubuntu)
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present
  when: ansible_lsb.id=="Ubuntu"

- name: Install packages (Ubuntu)
  apt: name={{ item }} state=present
  with_items:
    - lxc-docker
    - python-pip
    - dstat
    - tmux
    - git
    - build-essential
    - python-dev
    - sysstat
    - iptables
    - iptables-persistent
  when: ansible_lsb.id=="Ubuntu"

- name: Install packages (CentOS)
  yum: name={{ item }} state=present
  with_items:
    - docker
    - dstat
    - lsof
    - bash-completion
    - time
    - tmux
    - git
    - python-devel
    - sysstat
    - iptables-services
  when: ansible_lsb.id=="CentOS"

- name: Enable iptables service (CentOS)
  service: name=iptables state=started enabled=yes
  when: ansible_lsb.id=="CentOS"

- name: Upload custom docker configuration (CentOS)
  template:
    src=etc/sysconfig/{{ item }}.j2
    dest=/etc/sysconfig/{{ item }}
    backup=True
  with_items:
    - docker-network
  notify: restart docker
  when: ansible_lsb.id=="CentOS"

- name: Upload custom docker configuration (Ubuntu)
  template:
    src=etc/default/{{ item }}.j2
    dest=/etc/default/{{ item }}
    backup=True
  with_items:
    - docker
  notify: restart docker
  when: ansible_lsb.id=="Ubuntu"

- name: Enable Docker service
  service: name=docker state=started enabled=yes

- name: Install docker-py from pip (required by ansible, not available for Trusty as apt package, fixed version due to recent backward incompatible upgrade)
  pip: name=docker-py version=1.1.0

- name: Install ansible from pip
  pip: name=ansible version=1.9.0.1

- name: Add cloud-user to docker group and create ssh key
  user:
    name=cloud-user
    append=yes
    groups=docker
    generate_ssh_key=yes

- name: Create application root directory
  file: path={{ docker_host_app_root }} owner=cloud-user state=directory

- name: Create docker image directory
  file: path={{ docker_host_image_dir }} owner=cloud-user state=directory

- name: set iptables state file (CentOS)
  set_fact: iptables_state_file="/etc/sysconfig/iptables"
  when: ansible_lsb.id=="CentOS"

- name: set iptables state file (Ubuntu)
  set_fact: iptables_state_file="/etc/iptables/rules.v4"
  when: ansible_lsb.id=="Ubuntu"

- name: Iptables rules to block access to the host from containers
  template:
    src=etc/sysconfig/iptables.j2
    dest={{ iptables_state_file }}
    backup=True
  notify:
    - restart iptables
    - restart iptables-persistent

