language: python
python:
- '2.7'
- '3.4'

# for new container based Travis environment
sudo: false

install:
- pip install -r requirements.txt
- pip install flake8 --use-mirrors
- pip install .

- flake8 pouta_blueprints

script:
- python manage.py test

notifications:
  flowdock:
    secure: VteCDhr47oT0S2kST2s755cYJMVZachfn+utiPAasqxTiaFb+ZpxB7jR9Dt6BTIyPTkxfVYGpfJv8+6sM72ezQNETu6XmwCatQvVIQ8S5jdSb5uW6jv+0bcZbyBfK+D6xzEG/yBjy6UZGdwhYDmf+aUd1RR1GAzl6BBDtvRP3Vk=

env:
  global:
  - secure: aC1Z9lbous/dOTOCNhGGjz0mrhRFCTTpSwZyqlEQmkheEOkJhclhQRoecyADwsRKlGwOb1CSwmyuz5rjtd1MqbP8dpBKJwbJEgkezGCk75QokIdrPGV+zyNdcVYPvZgBXytiERIRxYmiL/rqVUWOELDvPI35LowolF1b5ENgzlg=
  - secure: FxVF7Khh7biG235ruvv7e5DfoasJM7hZrpzdycO24PqZhbQm5MpEoGEotbhaGxksFj4a0xePmZjFI9/GN87AD1HJ+IRqB8hC1yQXQoPM5UY6dqj9Gm14qr3D+6xUmjFbWdKotYz/mq9alT//tLr9Uf3qFxDHfk0B7o8qr8LpwKs=
