- name: Update key apt repositories (Ubuntu)
  template: src=etc/apt/sources.list.j2
            dest=/etc/apt/sources.list
            backup=yes
  when: ansible_lsb.id=="Ubuntu"

- name: Refresh repository metadata (Ubuntu)
  raw: apt-get update
  when: ansible_lsb.id=="Ubuntu"

- name: install python-apt (Ubuntu)
  raw: apt-get install python-apt -y -q
  when: ansible_lsb.id=="Ubuntu"

- name: Tools for debugging installation (Ubuntu)
  apt: pkg={{item}} state=present
  with_items:
    - dstat
    - lsof
    - bash-completion
    - time
  when: ansible_lsb.id=="Ubuntu"

- name: Tools for debugging installation (Centos)
  yum: name={{ item }} state=present
  with_items:
    - dstat
    - lsof
    - bash-completion
    - time
  when: ansible_lsb.id=="CentOS"

- name: Install dependencies (Ubuntu)
  apt: pkg={{item}} state=present
  with_items:
    - git
    - python
    - python-pip
    - python-dev
    - python-virtualenv
    - supervisor
  when: ansible_lsb.id=="Ubuntu"

- name: Install dependencies (CentOS)
  yum: name={{ item }} state=present
  with_items:
    - git
    - python
    - python-pip
    - python-dev
    - python-virtualenv
    - supervisor
  when: ansible_lsb.id=="CentOS"

- include: create_users_and_groups.yml
- include: setup_virtualenv.yml
- include: fetch_application.yml
- include: setup_supervisor.yml
- include: setup_runtime_directories.yml
