---

- name: install dependencies
  apt: pkg={{item}} state=present
  with_items:
    - redis-server
    - sqlite3

- name: install Shibboleth module for Apache
  apt: pkg=libapache2-mod-shib2 state=present
  when: enable_shibboleth == "True"

- name: install nginx
  apt: pkg=nginx state=present
  when: web_server_type == "nginx"

- name: install apache
  apt: pkg=apache2 state=present
  when: web_server_type == "apache"

- name: Set redis to listen to all interfaces
  lineinfile:
    name=/etc/redis/redis.conf
    regexp='^bind.*'
    state=absent

- name: Set redis not to daemonize
  shell: sed -i 's/^\(daemonize\s*\)yes\s*$/\1no/g' /etc/redis/redis.conf

- name: Disable redis-server on boot and make sure it is stopped - supervisord takes care of this
  service: name=redis-server enabled=false state=stopped

- include: setup_runtime_directories.yml
- include: setup_nginx.yml
  when: web_server_type == "nginx"
- include: setup_apache.yml
  when: web_server_type == "apache"
- include: setup_supervisor_config.yml
- include: setup_shibboleth.yml
  when: enable_shibboleth == "True"
