---

- name: Create the Nginx configuration file
  template: src=etc/nginx/sites-available/nginx_site_config.j2
            dest=/etc/nginx/sites-available/{{ application_name }}
            backup=yes

- name: Ensure that the default site is disabled
  command: rm /etc/nginx/sites-enabled/default
           removes=/etc/nginx/sites-enabled/default

- name: Ensure that the application site is enabled
  command: ln -s /etc/nginx/sites-available/{{ application_name }}
           /etc/nginx/sites-enabled/{{ application_name }}
           creates=/etc/nginx/sites-enabled/{{ application_name }}

- name: Link static root for nginx
  file:
    src={{ application_path }}/{{ application_name }}/static
    dest={{ nginx_static_root }}
    state=link
    # mode=775
    # owner={{ application_user }}
    # group={{ application_group }}

- name: Create provisioning log file root directory
  file:
    dest={{ provisioning_log_file_root }}
    mode=755 state=directory
    owner={{ application_user }}
    group={{ application_group }}

- name: Create ssl dir
  file:
    dest: /etc/nginx/ssl
    owner: root
    group: root
    mode: 0600
    state: directory

- name: Create self-signed SSL cert
  command: 
    openssl req -new -nodes -x509 -subj "/C=FI/ST=SouthernFinland/L=Helsinki/O=IT/CN={{ domain }}" -days 3650 -keyout {{ nginx_ssl_key }} -out {{ nginx_ssl_crt }} -extensions v3_ca 
    creates=/etc/nginx/ssl/server.crt
  notify: restart nginx

- name: Ensure Nginx service is stopped and disabled on boot - supervisord takes care of running it
  service: name=nginx state=stopped enabled=no

- name: disable Nginx running as daemon
  lineinfile:
        dest: /etc/nginx/nginx.conf
        state: present
        line: 'daemon off;'
