- name: Create ssl dir
  file:
    dest: "{{ docker_host_cert_dir }}"
    owner: root
    group: root
    mode: 0600
    state: directory

- name: Create self-signed SSL cert
  command: >
    openssl req -new -nodes -x509
    -subj "/C=FI/ST=SouthernFinland/L=Helsinki/O=IT/CN={{ domain_name }}"
    -days 3650
    -extensions v3_ca
    -keyout {{ docker_host_cert_dir }}/server.key
    -out {{ docker_host_cert_dir }}/server.crt
    creates={{ docker_host_cert_dir }}/server.crt
  register: self_signed_cert

- name: Use self-signed SSL cert as a dummy file for chain
  command: cp {{ docker_host_cert_dir }}/server.crt {{ docker_host_cert_dir }}/chain.crt
  when: self_signed_cert | changed

- name: make temporary directory for image build
  command: mktemp -d
  register: mktemp

- name: prepare docker image source (templates)
  template:
    src: "docker/{{ item }}.j2"
    dest: "{{mktemp.stdout}}/{{ item }}"
  with_items:
    - ansible-sudo
    - Dockerfile
    - supervisord.conf

- name: prepare docker image source (public key)
  copy: src=~/.ssh/id_rsa.pub dest={{ mktemp.stdout }}/id_rsa.pub

- name: check or build image
  docker_image: path={{ mktemp.stdout }} name={{ image_name }} state=present

- name: remove temp image build directory
  file: name={{ mktemp.stdout }} state=absent

  # command: chcon -Rt svirt_sandbox_file_t {{ docker_host_app_root }}
- name: Allow access to mounted host directories (CentOS)
  file:
    path: "{{ item }}"
    state: directory
    setype: svirt_sandbox_file_t
    recurse: yes
  with_items:
    - "{{ docker_host_app_root }}"
    - "{{ docker_host_image_dir }}"
    - "{{ docker_host_cert_dir }}"
  when: ansible_lsb.id=="CentOS"

# Avoid docker 1.8.2 with ansible 1.9.x pull bug
# see https://github.com/ansible/ansible-modules-core/issues/2043
- name: Pull images
  command: docker pull {{ item }}
  with_items:
    - "{{ docker_image_redis }}"
    - "{{ docker_image_postgres }}"

- name: Bring up container for db
  docker:
    name: db
    image: "{{ docker_image_postgres }}"
    state: running
    restart_policy: always
    env:
      POSTGRES_USER: "{{ application_database_user }}"
      POSTGRES_PASSWORD: "{{ application_database_password }}"

- name: Bring up container for redis
  docker:
    name: redis
    image: "{{ docker_image_redis }}"
    state: running
    restart_policy: always

- name: Bring up container for api
  docker:
    hostname: api
    image: "{{ image_name }}"
    state: running
    restart_policy: always
    name: api
    expose:
      - 22
      - "{{Â gunicorn_bind_port }}"
      - "{{ gunicorn_bind_port_worker }}"
    ports:
      - "2222:22"
    links:
      - "db:db"
      - "redis:redis"
    volumes:
      - "{{ docker_host_app_root }}:/shared_folder/source:ro"
      - "{{ provisioning_log_file_root }}"

- name: add api to inventory
  add_host:
    name: api
    groups: docker,api
    ansible_ssh_host: localhost
    ansible_ssh_port: 2222
    ansible_ssh_user: ansible
  ## see https://github.com/ansible/ansible-modules-core/issues/1005
  # when: item.Config.Hostname == "www" and item.State.Running == True
  # with_items: docker_containers


- name: Bring up container for sso
  docker:
    hostname: sso
    image: "{{ image_name }}"
    state: running
    restart_policy: always
    name: sso
    expose:
      - 80
    ports:
      - "2225:22"
    links:
      - "api:api"
    volumes:
      - "{{ docker_host_sso_dir }}:/etc/{{ application_name }}/sso:ro"
  when: "{{ enable_shibboleth | bool }}"

- name: add sso to inventory
  add_host:
    name: sso
    groups: docker,sso
    ansible_ssh_host: localhost
    ansible_ssh_port: 2225
    ansible_ssh_user: ansible
  when: "{{ enable_shibboleth | bool }}"

- name: define frontend links
  set_fact:
    frontend_links: "['api:api', 'redis:redis']"
  when: "{{ not enable_shibboleth | bool }}"

- name: define frontend links (shibboleth enabled)
  set_fact:
    frontend_links: "['api:api', 'redis:redis', 'sso:sso']"
  when: "{{ enable_shibboleth | bool }}"

- name: Bring up container for frontend
  docker:
    hostname: frontend
    image: "{{ image_name }}"
    state: running
    restart_policy: always
    name: frontend
    expose:
      - 22
      - 80
      - "{{ application_external_https_port }}"
    ports:
      - "2224:22"
      - "80:80"
      - "{{ application_external_https_port }}:{{ application_external_https_port }}"
    links: "{{ frontend_links }}"
    volumes:
      - "{{ docker_host_cert_dir }}:/etc/nginx/ssl:ro"
    volumes_from:
      - api:ro

- name: add frontend to inventory
  add_host:
    name: frontend
    groups: docker,frontend
    ansible_ssh_host: localhost
    ansible_ssh_port: 2224
    ansible_ssh_user: ansible


- name: Bring up container for worker
  docker:
    hostname: worker
    image: "{{ image_name }}"
    state: running
    restart_policy: always
    name: worker
    expose:
      - 22
    ports:
      - "2223:22"
    links:
      - "api:api"
      - "redis:redis"
    volumes:
      - "{{ docker_host_app_root }}:/shared_folder/source:ro"
      - "{{ docker_host_m2m_credentials_dir }}:{{ application_m2m_credentials_dir }}:ro"
      - "{{ docker_host_image_dir }}:/images:ro"

- name: add worker to inventory
  add_host:
    name: worker
    groups: docker,worker
    ansible_ssh_host: localhost
    ansible_ssh_port: 2223
    ansible_ssh_user: ansible
  ## see https://github.com/ansible/ansible-modules-core/issues/1005
  # when: item.config.hostname == "worker" and item.state.running == True
  # with_items: docker_containers

- name: "Wait a bit for sshd to come up"
  pause: seconds=5
