apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{name}"
spec:
  rules:
    - host: "{host}"
      http:
        paths:
          - backend:
              serviceName: "{name}"
              servicePort: 8888
